CREATE TABLE vehiculos (
    id BIGINT NOT NULL AUTO_INCREMENT,
    marca VARCHAR(100) NOT NULL,
    modelo VARCHAR(255) NOT NULL,
    annio INT NOT NULL,
    placa VARCHAR(10) NOT NULL UNIQUE,
    precio INT NOT NULL,
    PRIMARY KEY (id)
);
